packaging_format = 2

id = "forgejo"
name = "Forgejo"
description.en = "Lightweight software forge"
description.fr = "Forge logiciel légère"

version = "1.19.3-0~ynh1"

maintainers = ["Emmanuel Averty"]

[upstream]
license = "MIT"
website = "https://forgejo.org"
admindoc = "https://docs.gitea.io/"
code = "https://codeberg.org/forgejo/forgejo"
cpe = "???" 
fund = "???" 

[integration]
yunohost = ">= 11.0.9"
architectures = ["amd64", "arm64", "armhf"] 
multi_instance = true
ldap = true 
sso = "not_relevant" 
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "domain"

    [install.path]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "path"
    default = "/forgejo"

    [install.admin]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "user"

    [install.init_main_permission]
    help.en = "If enabled, Forgejo will be accessible by people who do not have an account. This can be changed later via the webadmin."
    help.fr = "Si cette case est cochée, Forgejo sera accessible aux personnes n'ayant pas de compte. Vous pourrez changer ceci plus tard via la webadmin."
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        armhf.url = "https://codeberg.org/attachments/cff7ed0a-a842-4c93-893c-311087c11e17"
        armhf.sha256 = "b647b675cb71e7830d7788b4dca5aa33a361b1a50e4bfe9d751a77f68a9acad2"
        arm64.url = "https://codeberg.org/attachments/f6b50aec-d098-4667-9c8b-e0b80a940139"
        arm64.sha256 = "92057d4e09ef25cd2d01ad31cf0619ac93aa667ced4df9ae21c5b87dd5af3e1b"
        amd64.url = "https://codeberg.org/attachments/25eea495-ba85-4061-bec0-cf9823b63cb2"
        amd64.sha256 = "1184549434200479f910457910bb63f1a5a8781152e6364eb6c9b3235b489e57"
        rename = "forgejo"
        extract = false


    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 6000

    [resources.apt]
    packages = "postgresql"

    [resources.database]
    type = "postgresql"
